# Esta es la importación de tus rutas de controlador (por atributos)
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Esta ruta intercepta la URL raíz "/" y la redirige permanentemente (301)
# a la ruta nombrada 'app_login' definida en tu SecurityController.
redirect_root_to_login:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_login
        permanent: true
